"""
pdf_gen.py — Generate seating PDF using fpdf2
"""

from fpdf import FPDF
from typing import List, Optional, Dict
import io


def generate_pdf(grid: List[List[Optional[Dict]]], exam_name: str, rows: int, cols: int) -> bytes:
    pdf = FPDF(orientation="L", unit="mm", format="A4")
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=10)

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"Exam Seating Plan - {exam_name}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 6, f"Room: {rows} rows x {cols} columns  |  Anti-Cheat Arrangement", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Calculate cell width to fit page
    page_width = pdf.w - 20  # margins
    cell_w = min(page_width / cols, 55)
    cell_h = 18

    # Subject color mapping (text label only, no color in PDF for simplicity)
    subjects = set()
    for row in grid:
        for cell in row:
            if cell:
                subjects.add(cell["subject"])
    subject_list = sorted(subjects)

    # Legend
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "Subjects: " + "  |  ".join(subject_list), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Draw grid
    for r, row in enumerate(grid):
        # Row label
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(220, 220, 220)
        pdf.cell(10, cell_h, f"R{r+1}", border=1, align="C", fill=True)

        for c, student in enumerate(row):
            seat_no = r * cols + c + 1

            if student:
                # Alternate fill for readability
                fill = (240, 248, 255) if (r + c) % 2 == 0 else (255, 255, 255)
                pdf.set_fill_color(*fill)

                # Draw cell with border
                x = pdf.get_x()
                y = pdf.get_y()
                pdf.rect(x, y, cell_w, cell_h, style="FD")

                # Seat number (small, top-left)
                pdf.set_font("Helvetica", "", 6)
                pdf.set_xy(x + 1, y + 1)
                pdf.cell(cell_w - 2, 4, f"#{seat_no}", align="L")

                # Student name
                pdf.set_font("Helvetica", "B", 7)
                pdf.set_xy(x + 1, y + 5)
                name = student["name"][:14] if len(student["name"]) > 14 else student["name"]
                pdf.cell(cell_w - 2, 4, name, align="C")

                # Roll number
                pdf.set_font("Helvetica", "", 6)
                pdf.set_xy(x + 1, y + 9)
                pdf.cell(cell_w - 2, 3, f"Roll: {student['roll']}", align="C")

                # Subject
                pdf.set_font("Helvetica", "I", 6)
                pdf.set_xy(x + 1, y + 13)
                subj = student["subject"][:12] if len(student["subject"]) > 12 else student["subject"]
                pdf.cell(cell_w - 2, 3, subj, align="C")

                pdf.set_xy(x + cell_w, y)
            else:
                # Empty seat
                pdf.set_fill_color(245, 245, 245)
                pdf.set_font("Helvetica", "I", 7)
                pdf.cell(cell_w, cell_h, f"#{seat_no} Empty", border=1, align="C", fill=True)

        pdf.ln(cell_h)

    # Footer
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by Exam Seating System - Anti-Cheat Arrangement", align="C")

    return bytes(pdf.output())




if __name__ == "__main__":
    from seating import generate_seating
    students = [
        {"name": "Amit",  "roll": "101", "subject": "Maths"},
        {"name": "Priya", "roll": "102", "subject": "Physics"},
        {"name": "Rahul", "roll": "103", "subject": "Chemistry"},
        {"name": "Neha",  "roll": "104", "subject": "Maths"},
    ]
    grid = generate_seating(students, 2, 2)
    pdf = generate_pdf(grid, "Test Exam", 2, 2)
    with open("test_output.pdf", "wb") as f:
        f.write(pdf)
    print(f"PDF created: {len(pdf)} bytes")